rm(list = ls())
source('~/Documents/R_Codes/Offsets_Working_FEB_3/offsets_functions_current.R')
source('~/Documents/R_Codes/Offsets_Working_FEB_3/Global_Regional_Params.R')
.libPaths('~/Library/R/3.2/library')
library(foreach)
library(doParallel)
library(abind)
graphics.off()
global_params <- initialise_global_params()
region_params <- initialise_region_params(global_params$region_num, restoration_rate = 0.03, mean_decline_rates = c(0.03, 0.01), global_params$time_steps, global_params$total_dev_num)
parcels <- initialise_shape_parcels(global_params)
index_object <- initialise_index_object(parcels, global_params)
initial_ecology <- initialise_ecology(global_params, parcels)
decline_rates_initial <- build_decline_rates_multi(parcels, region_params, global_params$eco_dims)
outputs <- calc_trajectories_multi(global_params, region_params, current_ecology = initial_ecology, decline_rates = decline_rates_initial, 
                                   parcels, index_object, perform_offsets = TRUE, record_parcel_sets = TRUE)

parcel_sets_object <- find_parcel_sets(outputs, land_parcels, time_steps, decline_rates_initial)
collated_parcel_sets_object <- collate_parcel_sets(parcel_sets_object, global_params$time_steps, global_params$eco_dims)

cfacs <- build_counterfactuals_by_parcel_multi(global_params, decline_rates_initial, 1:(parcels$land_parcel_num), parcels$land_parcels, initial_ecology, time_steps = global_params$time_steps)
cfac_parcel_trajs <- find_parcel_traj_by_list(cfacs[[1]])
parcel_trajs <- find_parcel_trajectories(parcels$land_parcels, 1:(parcels$land_parcel_num), global_params$time_steps, outputs$trajectories[[1]])
plot_single_net_regional(collated_parcel_sets_object, assessed_set_index = 5, global_params, cfac_parcel_trajs, parcel_trajs)

