current_combination_params <-
structure(list(offset_action_params = list(c("avoided_loss", 
"maintain")), dev_calc_type = "future_condition", allow_developments_from_credit = TRUE, 
    development_selection_type = "random", use_offset_bank = FALSE, 
    offset_bank_start = 1, offset_bank_end = 1, offset_bank_num = 200, 
    offset_bank_type = "credit", site_for_site = FALSE, offset_time_horizon = 15, 
    include_potential_developments_in_offset_calc = TRUE, include_illegal_clearing_in_offset_calc = TRUE, 
    include_potential_offsets_in_offset_calc = FALSE, dev_counterfactual_adjustment = "as_offset", 
    offset_multiplier = 1, offset_time_horizon_type = "future", 
    offset_calc_type = "avoided_loss", offset_action_type = "maintain", 
    use_parcel_sets = TRUE, match_type = "parcel_set", use_offset_time_horizon = TRUE, 
    offset_cfacs_flag = TRUE, offset_restoration_flag = FALSE, 
    dev_cfacs_flag = TRUE, banked_offset_vec = list(), include_potential_developments_in_dev_calc = TRUE, 
    include_potential_offsets_in_dev_calc = FALSE, include_illegal_clearing_in_dev_calc = TRUE, 
    adjust_offset_cfacs_flag = TRUE, adjust_dev_cfacs_flag = TRUE), .Names = c("offset_action_params", 
"dev_calc_type", "allow_developments_from_credit", "development_selection_type", 
"use_offset_bank", "offset_bank_start", "offset_bank_end", "offset_bank_num", 
"offset_bank_type", "site_for_site", "offset_time_horizon", "include_potential_developments_in_offset_calc", 
"include_illegal_clearing_in_offset_calc", "include_potential_offsets_in_offset_calc", 
"dev_counterfactual_adjustment", "offset_multiplier", "offset_time_horizon_type", 
"offset_calc_type", "offset_action_type", "use_parcel_sets", 
"match_type", "use_offset_time_horizon", "offset_cfacs_flag", 
"offset_restoration_flag", "dev_cfacs_flag", "banked_offset_vec", 
"include_potential_developments_in_dev_calc", "include_potential_offsets_in_dev_calc", 
"include_illegal_clearing_in_dev_calc", "adjust_offset_cfacs_flag", 
"adjust_dev_cfacs_flag"))
