global_params <-
structure(list(simulated_ecology_user_params_file = "default", 
    overwrite_default_params = TRUE, simulation_folder = "/Users/E24661/GitHub/offset_simulator/user_examples/grasslands", 
    use_simulated_data = FALSE, unique_simulation_folder = TRUE, 
    realisation_num = 1, number_of_cores = 1, time_steps = 50, 
    dev_start = 1, dev_end = 50, total_dev_num = 50, save_simulation_outputs = FALSE, 
    overwrite_existing_landscape_data = TRUE, run_from_saved = FALSE, 
    backup_simulation_inputs = TRUE, write_movie = TRUE, write_offset_layer = FALSE, 
    features_to_use_in_offset_calc = 1, features_to_use_in_simulation = 1, 
    max_offset_parcel_num = 20, sample_restoration_rate = FALSE, 
    sample_decline_rate = FALSE, limit_offset_restoration = TRUE, 
    illegal_clearing_prob = 0.001, landscape_evolve_type = "static", 
    rescale_ecology_to_feature_subset = TRUE, mean_decline_rates = list(
        1), decline_rate_std = list(0), min_eco_val = 0, max_eco_val = 100, 
    screen_sites_by_size = TRUE, screen_site_zeros = TRUE, site_screen_size = 50, 
    screen_dev_site_zeros = FALSE, screen_offset_site_zeros = TRUE, 
    set_seed = FALSE, match_threshold = 0, max_restoration_eco_val = 70, 
    restoration_rate_params = c(0.02, 0.005), apply_offset_exclusion_layer = TRUE, 
    offset_exclusion_layer_filename = "protected_areas.rds", 
    apply_development_exclusion_layer = TRUE, dev_exclusion_layer_filename = "protected_areas.rds", 
    strt = structure(1513816623.3866, class = c("POSIXct", "POSIXt"
    )), run_folder = "/Users/E24661/GitHub/offset_simulator/user_examples/grasslands/simulation_runs/00001/", 
    output_folder = "/Users/E24661/GitHub/offset_simulator/user_examples/grasslands/simulation_runs/00001//simulation_outputs/", 
    simulation_params_folder = "/Users/E24661/GitHub/offset_simulator/user_examples/grasslands/simulation_runs/00001//simulation_params/", 
    simulation_inputs_folder = "/Users/E24661/GitHub/offset_simulator/user_examples/grasslands/simulation_inputs/", 
    collated_folder = "/Users/E24661/GitHub/offset_simulator/user_examples/grasslands/simulation_runs/00001/collated_outputs/", 
    feature_num = 1L, intervention_vec = structure(c(1, 0, 2, 
    1, 2, 1, 0, 2, 3, 0, 0, 0, 0, 0, 0, 2, 1, 0, 1, 1, 2, 0, 
    2, 2, 0, 2, 2, 2, 0, 2, 0, 1, 0, 1, 1, 1, 0, 0, 3, 1, 0, 
    3, 2, 0, 0, 0, 2, 2, 2, 0), .Dim = 50L)), .Names = c("simulated_ecology_user_params_file", 
"overwrite_default_params", "simulation_folder", "use_simulated_data", 
"unique_simulation_folder", "realisation_num", "number_of_cores", 
"time_steps", "dev_start", "dev_end", "total_dev_num", "save_simulation_outputs", 
"overwrite_existing_landscape_data", "run_from_saved", "backup_simulation_inputs", 
"write_movie", "write_offset_layer", "features_to_use_in_offset_calc", 
"features_to_use_in_simulation", "max_offset_parcel_num", "sample_restoration_rate", 
"sample_decline_rate", "limit_offset_restoration", "illegal_clearing_prob", 
"landscape_evolve_type", "rescale_ecology_to_feature_subset", 
"mean_decline_rates", "decline_rate_std", "min_eco_val", "max_eco_val", 
"screen_sites_by_size", "screen_site_zeros", "site_screen_size", 
"screen_dev_site_zeros", "screen_offset_site_zeros", "set_seed", 
"match_threshold", "max_restoration_eco_val", "restoration_rate_params", 
"apply_offset_exclusion_layer", "offset_exclusion_layer_filename", 
"apply_development_exclusion_layer", "dev_exclusion_layer_filename", 
"strt", "run_folder", "output_folder", "simulation_params_folder", 
"simulation_inputs_folder", "collated_folder", "feature_num", 
"intervention_vec"))
